name: Update readme

on: 
  push:
    paths: 
      - 'where-is-top250.csv'
      - 'script.js'
      - '.github/workflows/updateInfo.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: update readme
      run: |
        npm install
        node script.js
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update README after adding movie(s)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
